# Generated by Django 4.1.5 on 2023-01-19 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_product_remove_cartitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cartitem'),
        ),
    ]
